### ISSUE TITLE
运行以后无反应

### ISSUE THREAD

**Issue by createalltheworld** [windy-purple/dumpshell#1]
为啥运行了以后不报错但是也没有反应，相应的存储路径下也没生成任何的文件夹

**Comment by windy-purple** [comment]
脚本仅支持特定的安卓版本，请先检查脚本内部的函数签名是否与运行的安卓机器内部函数签名是否一致

**Comment by windy-purple** [comment]
脚本仅支持特定的安卓版本，请先检查脚本内部的函数签名是否与运行的安卓机器内部函数签名是否一致
