### ISSUE TITLE
麻烦更新下脚本，支持安卓10

### ISSUE THREAD

**Issue by bike3097a** [windy-purple/dumpshell#2]
附体，另外针对某些混淆的有没有改进呀，最后例如被360加固，把一些方法抽取了，用native填充了，能不能解决呀。

**Comment by windy-purple** [comment]
安卓10请自行寻找脱壳函数，替换脚本中的54行的函数签名即可，另外，本脚本只是用作脱壳，不负责修复

**Comment by bike3097a** [comment]
有没有教程呀 我不知道函数签名哦

**Comment by windy-purple** [comment]
可以去看雪看一下寒冰大佬的文章
